[package]
name = "bereal-data-transform"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
chrono-tz = "0.9.0"
clap = { version = "4.5.11", features = ["derive"] }
regex = "1.10.5"
serde ={ version ="1.0.204", features = ["derive"] }
serde_json = "1.0.120"
